version: 0.2

env:
  variables:
    OS: debian
    RELEASE: buster
    NGINX_VERSION: 1.18.0
    NGINX_DEB_RELEASE: 2

batch:
  fast-fail: false
  build-list:
    - identifier: x86_64
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        compute-type: BUILD_GENERAL1_LARGE
      ignore-failure: true
    - identifier: arm64
      env:
        type: ARM_CONTAINER
        privileged-mode: true
        image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
        compute-type: BUILD_GENERAL1_LARGE

phases:
  pre_build:
    commands:
      # Docker Hub へのログイン
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
      # コミット ID をイメージタグに設定
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - DOCKER_BUILDKIT=1 docker build -t build-nginx-brotli -f Dockerfile-deb --build-arg DISTRIB=${OS} --build-arg RELEASE=${RELEASE} --build-arg NGINX_VERSION=${NGINX_VERSION} --build-arg NGINX_DEB_RELEASE=${NGINX_DEB_RELEASE} .
  post_build:
    commands:
      - docker run build-nginx-brotli
      - docker cp $(docker ps -l -q):/src .
      - mv src/*deb .

artifacts:
  files:
    - "*.deb"
